#!/usr/bin/env node
// Reads top-level MOC files from ../content/ and writes a compact snapshot
// to moc-snapshot.js for injection into the AI system prompt.
// Usage: node cloudflare-worker/build-context.mjs

import { readFileSync, writeFileSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"

const __dir = dirname(fileURLToPath(import.meta.url))
const contentDir = join(__dir, "..", "content")

const MOC_FILES = [
  "01 Projects/01 Projects MOC.md",
  "01 Projects/Visustwin/MOC.md",
  "02 Areas/02 Areas MOC.md",
  "03 Products/03 Products MOC.md",
  "03 Products/Visustwin Extensions/Visustwin Extensions MOC.md",
  "04 Resources/04 Resources MOC.md",
]

const MAX_BYTES = 3000

function extractSnapshot(filePath, label) {
  let raw
  try {
    raw = readFileSync(join(contentDir, filePath), "utf8")
  } catch {
    return ""
  }

  // Strip YAML frontmatter
  raw = raw.replace(/^---[\s\S]*?---\n?/, "")

  const lines = raw.split("\n")
  const out = [`### ${label}`]
  let charCount = 0

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) continue
    // Keep headings and first paragraph text; skip wikilinks-only lines
    const isHeading = trimmed.startsWith("#")
    const isLinkOnly = /^\[\[.*\]\]$/.test(trimmed)
    if (isHeading || (!isLinkOnly && !trimmed.startsWith("|") && !trimmed.startsWith("!"))) {
      out.push(trimmed)
      charCount += trimmed.length
      if (charCount > 600) break
    }
  }

  return out.join("\n")
}

const LABEL_MAP = {
  "01 Projects/01 Projects MOC.md":                          "Projects (index)",
  "01 Projects/Visustwin/MOC.md":                           "Visustwin Project",
  "02 Areas/02 Areas MOC.md":                               "Areas (index)",
  "03 Products/03 Products MOC.md":                         "Products (index)",
  "03 Products/Visustwin Extensions/Visustwin Extensions MOC.md": "Visustwin Extensions",
  "04 Resources/04 Resources MOC.md":                       "Resources (index)",
}

let snapshot = "## Vault MOC Snapshot\n\n"
for (const f of MOC_FILES) {
  const section = extractSnapshot(f, LABEL_MAP[f])
  if (!section) continue
  snapshot += section + "\n\n"
  if (snapshot.length > MAX_BYTES) break
}
snapshot = snapshot.trimEnd()

const output = `// Auto-generated by build-context.mjs — do not edit manually.
// Run \`node cloudflare-worker/build-context.mjs\` to refresh.
export const MOC_SNAPSHOT = ${JSON.stringify(snapshot)}
`

const outPath = join(__dir, "moc-snapshot.js")
writeFileSync(outPath, output, "utf8")
console.log(`✓ moc-snapshot.js written (${output.length} bytes)`)
